services:
  production-analysis-backend:
    image: antspring/production-analysis-backend
    container_name: backend
    ports:
      - "${BACKEND_EXTERNAL_PORT}:${BACKEND_INTERNAL_PORT}"
    env_file:
      - .env
    depends_on:
      - migrate

  migrate:
    image: antspring/production-analysis-migrate
    container_name: migrate
    env_file:
      - .env
    depends_on:
      - postgres
    restart: "no"

  postgres:
    image: postgres:18
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:${POSTGRES_INTERNAL_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/18/main

volumes:
  postgres_data:
